# Generated by Django 2.1.7 on 2019-03-25 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe_name', models.CharField(max_length=15)),
                ('clothe_file', models.FileField(upload_to='')),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fashionapp.Clothe')),
            ],
        ),
    ]
