# Generated by Django 2.1.7 on 2019-05-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashionapp', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
